---
site_name: datatrail-cli

nav:
  - Home:
      - Datatrail CLI: index.md
  - User Guide:
      - Welcome: user_guide.md
      - Install: install.md
      - Initialize: initialising.md
      - Recursive discovery: discovery.md
      - Commands:
          - clear: clear.md
          - doctor: doctor.md
          - inventory: inventory.md
          - list: list.md
          - ps: ps.md
          - pull: pull.md
          - pull-manifest: pull-manifest.md
          - scout: scout.md
          - unregistered: unregistered.md
          - verify: verify.md
  - Command Line Interface:
      - Commands: commands.md
      - Reference: cli.md
