---
site_name: datatrail-cli

nav:
  - Home:
      - Datatrail CLI: index.md
  - User Guide:
      - Welcome: user_guide.md
      - Install: install.md
      - Initialise: initialising.md
      - Commands:
          - clear: clear.md
          - list: list.md
          - ps: ps.md
          - pull: pull.md
          - scout: scout.md
  - Command Line Interface:
      - Commands: commands.md
      - Reference: cli.md
