on:
  push:
    branches:
      - main
name: Continuous Deployment
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: release-please
        uses: googleapis/release-please-action@v5

      - name: Checkout code
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Install uv
        if: ${{ steps.release-please.outputs.release_created }}
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: false
          python-version: "3.13"

      - name: Build datatrail-cli
        if: ${{ steps.release-please.outputs.release_created }}
        run: uv build

      - name: Publish to pypi
        if: ${{ steps.release-please.outputs.release_created }}
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish --verbose
