name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install poetry
      - run: poetry install --without dev
      - run: poetry run mkdocs gh-deploy --force
