name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Build chimefrb/handbook
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BUILD_HANDBOOK_TOKEN }}
          repository: chimefrb/handbook
          event-type: build-handbook
          client-payload: '{"source": "chimefrb/datatrail-cli"}'
