name: Close Stale Issues and Pull Requests

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale pull requests
        uses: actions/stale@v9
        with:
          days-before-stale: 90
          days-before-close: 7
          close-issue-message: "This pull request has been automatically closed. Please reopen if you feel this issue is still relevant."
          stale-issue-message: "This pull request has been automatically marked as 'Stale' because it has been inactive for more than 90 days. If there is no interaction here, this issue will be closed in seven days."
          stale-issue-label: Stale
          close-pr-message: "This pull request has been automatically closed because it has been inactive for more than 90 days."
          stale-pr-message: "This pull request has been marked as stale because it has been inactive for more than 90 days. Please update this pull request or it will be automatically closed in seven days."
          stale-pr-label: Stale
